package de.freegroup.digitalsimulator.export.wired.util.db;

/**
 * short-i Class generated by automatic ClassGenerator
 * Date: 2002-10-04
 */
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;

import de.freegroup.digitalsimulator.db.*;

public class CreateDB { 
	public static void main ( String[] args )
	{
		try
		{
			SaveConnection conn=ConnectionManager.getValid();
			SaveStatement  stat=conn.createStatement("createDB");
		try {
			stat.executeUpdate("DROP TABLE RelatedObject");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE RelatedObject ("+
			"relatedObject_id  VARCHAR(50)  NOT NULL  , "+
			"masterObject_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE ElectricObject");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE ElectricObject ("+
			"isSingelton  int  NOT NULL  , "+
			"type  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE ObjectPin");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE ObjectPin ("+
			"object2Case_id  VARCHAR(50)  NOT NULL  , "+
			"description  VARCHAR(50)  NOT NULL  , "+
			"number  bigint  NOT NULL  , "+
			"casePin_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE CaseLayout");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE CaseLayout ("+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE MacroPinMapping");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE MacroPinMapping ("+
			"relatedObjectPinNum  bigint  NOT NULL  , "+
			"relatedObject_id  VARCHAR(50)  NOT NULL  , "+
			"electricObjectPinNum  bigint  NOT NULL  , "+
			"electricObject_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE Object2Case");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE Object2Case ("+
			"electricCase_id  VARCHAR(50)  NOT NULL  , "+
			"object_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE DependencyPin");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE DependencyPin ("+
			"caseDependency_id  VARCHAR(50)  NOT NULL  , "+
			"objectPin_id  VARCHAR(50)  NOT NULL  , "+
			"casePin_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE ElectricCase");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE ElectricCase ("+
			"name  VARCHAR(50)  NOT NULL  , "+
			"descriptionURL  VARCHAR(50)  NOT NULL  , "+
			"caseLayout_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE CaseDependency");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE CaseDependency ("+
			"electricCase_id  VARCHAR(50)  NOT NULL  , "+
			"object_id  VARCHAR(50)  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE CasePin");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE CasePin ("+
			"x  bigint  NOT NULL  , "+
			"description  VARCHAR(50)  NOT NULL  , "+
			"number  bigint  NOT NULL  , "+
			"caseLayout_id  VARCHAR(50)  NOT NULL  , "+
			"y  bigint  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
		try {
			stat.executeUpdate("DROP TABLE Connection");
		} catch(SQLException e) {}// Ignore Exception, because the table may not yet exist
		stat.execute("CREATE TABLE Connection ("+
			"fromRelatedObject_id  VARCHAR(50)  NOT NULL  , "+
			"fromPinNuum  int  NOT NULL  , "+
			"toRelatedObject_id  VARCHAR(50)  NOT NULL  , "+
			"toPinNum  int  NOT NULL  , "+
			"id  VARCHAR(50)  NOT NULL  , "+
			"PRIMARY KEY    (id))");
			stat.close();
		}
		catch(Exception exc)
		{
			System.out.println(exc);
			exc.printStackTrace();
		}
	}
}
