/* NO WARRANTY
 *
 *    BECAUSE THE PROGRAM IS IN THE PUBLIC DOMAIN, THERE IS NO
 *    WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE
 *    LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE AUTHORS
 *    AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT
 *    WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *    BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
 *    THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD
 *    THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 *    NECESSARY SERVICING, REPAIR OR CORRECTION.
 *
 *    IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN
 *    WRITING WILL ANY AUTHOR, OR ANY OTHER PARTY WHO MAY MODIFY
 *    AND/OR REDISTRIBUTE THE PROGRAM, BE LIABLE TO YOU FOR DAMAGES,
 *    INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL
 *    DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
 *    RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES
 *    OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER
 *    PROGRAMS), EVEN IF SUCH AUTHOR OR OTHER PARTY HAS BEEN ADVISED
 *    OF THE POSSIBILITY OF SUCH DAMAGES.
 */
#if !defined(AFX_DRAGDROPCURSORMANAGER_H__BB5C5B92_2814_11D4_B599_004F49031E0C__INCLUDED_)
#define AFX_DRAGDROPCURSORMANAGER_H__BB5C5B92_2814_11D4_B599_004F49031E0C__INCLUDED_


#pragma warning(disable : 4786)
#include <map>
//using namespace std ;

typedef    std::map<int, HCURSOR> CursorMap;

class DragDropCursorManager  {
public:
    enum Type {
      ARROW   = IDC_ARROW,
      IBEAM   = IDC_IBEAM,
      WAIT    = IDC_WAIT,
      CROSS   = IDC_CROSS,
      UPARROW = IDC_UPARROW,
      SIZE    = IDC_SIZEALL,
      ICON    = IDC_ARROW,
      SIZENWSE= IDC_SIZENWSE,
      SIZENESW= IDC_SIZENESW,
      SIZEWE  = IDC_SIZEWE,
      SIZENS  = IDC_SIZENS,
      NODROP  = IDC_NO,
      };

   static void set(DragDropCursorManager::Type  );
protected:
   static CursorMap  m_cursors;
};

typedef  DragDropCursorManager CM;

#endif // !defined(AFX_DRAGDROPCURSORMANAGER_H__BB5C5B92_2814_11D4_B599_004F49031E0C__INCLUDED_)
