/* NO WARRANTY
 *
 *    BECAUSE THE PROGRAM IS IN THE PUBLIC DOMAIN, THERE IS NO
 *    WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE
 *    LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE AUTHORS
 *    AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT
 *    WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *    BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
 *    THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD
 *    THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 *    NECESSARY SERVICING, REPAIR OR CORRECTION.
 *
 *    IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN
 *    WRITING WILL ANY AUTHOR, OR ANY OTHER PARTY WHO MAY MODIFY
 *    AND/OR REDISTRIBUTE THE PROGRAM, BE LIABLE TO YOU FOR DAMAGES,
 *    INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL
 *    DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM
 *    (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
 *    RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES
 *    OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER
 *    PROGRAMS), EVEN IF SUCH AUTHOR OR OTHER PARTY HAS BEEN ADVISED
 *    OF THE POSSIBILITY OF SUCH DAMAGES.
 */

#if !defined(AFX_DIGITALTRAINEESTUDIODOC_H__94F3F5EF_6114_11D2_890F_004F49031E0C__INCLUDED_)
#define AFX_DIGITALTRAINEESTUDIODOC_H__94F3F5EF_6114_11D2_890F_004F49031E0C__INCLUDED_
#pragma warning(disable : 4786)


#include "DragDropDocument.h"

class CDigitalTraineeStudioDoc : public DragDropDocument{
   typedef DragDropDocument inherited;

protected: // Nur aus Serialisierung erzeugen
	CDigitalTraineeStudioDoc();
	DECLARE_DYNCREATE(CDigitalTraineeStudioDoc)

public:
   virtual void Serialize(CArchive& ar);
   virtual BOOL SaveModified( );
   virtual CString ToXML();
   virtual CString ToXML(CString pathToCircuit, CString pathToCircuitImage);

	//{{AFX_VIRTUAL(CDigitalTraineeStudioDoc)
	protected:
	virtual BOOL OnNewDocument();
	//}}AFX_VIRTUAL

	virtual ~CDigitalTraineeStudioDoc();
   virtual char * const GetClassName(){return "CDigitalTraineeStudioDoc";};

};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio fügt zusätzliche Deklarationen unmittelbar vor der vorhergehenden Zeile ein.

#endif // !defined(AFX_DIGITALTRAINEESTUDIODOC_H__94F3F5EF_6114_11D2_890F_004F49031E0C__INCLUDED_)
