//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DigitalTrainingStudio.rc
//
#define IDB_ANIMATED_ICON               100
#define IDB_BACKGROUND                  101
#define IDP_OLE_INIT_FAILED             101
#define IDB_BITMAP_HSB                  102
#define IDP_FAILED_TO_CREATE            102
#define CG_IDR_POPUP_OBJECT_TOOL_BAR    103
#define IDB_BITMAP_RGB                  103
#define IDB_BITMAP1                     104
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_CONNECT_COSIVIS             105
#define CG_IDR_POPUP_CHILD_FRAME        106
#define IDB_CONNECT_EASYPORT            106
#define IDB_CONNECT_EXCEL               107
#define IDB_CONNECT_EZDDE               108
#define IDB_CONNECT_START               109
#define IDB_CONNECT_UNKNOWN             110
#define IDB_CROSS_GRID                  111
#define IDB_DDE_PROPERTIES_COSIVIS      112
#define IDB_DDE_PROPERTIES_EXCEL        113
#define IDB_DDE_PROPERTIES_EZDDE        114
#define IDB_DDE_PROPERTIES_UNKNOWN      115
#define IDB_DDEIN_END_PAGE              116
#define IDB_DDEIN_PROPERTIES_COSIVIS    117
#define IDB_DDEIN_PROPERTIES_EASYPORT   118
#define IDB_DDEIN_PROPERTIES_EXCEL      119
#define IDB_DDEIN_PROPERTIES_UNKNOWN    120
#define IDB_DDEIN_START_PAGE            121
#define IDB_DDEOUT_END_PAGE             122
#define IDB_DDEOUT_PROPERTIES_COSIVIS   123
#define IDB_DDEOUT_PROPERTIES_EASYPORT  124
#define IDB_DDEOUT_PROPERTIES_EXCEL     125
#define IDB_DDEOUT_PROPERTIES_UNKNOWN   126
#define IDB_DDEOUT_START_PAGE           127
#define IDB_DEMULTIPLEXER               128
#define IDB_DIVIDER_PARAM               129
#define IDB_DOT_GRID                    130
#define IDB_INPUT_OUTPUT_OBJECT         131
#define IDB_LINE_GRID                   132
#define IDB_MULTIPLEXER                 133
#define IDB_POWERTASTER_DEFAULT_OFF     134
#define IDB_POWERTASTER_DEFAULT_ON      135
#define IDB_SIMPLE_PORTS                136
#define IDB_SIMPLE_PORTS_MASK           137
#define IDB_SPLASH_SCREEN               138
#define IDB_TAB_CTRL                    139
#define IDB_TAKT_PARAM                  140
#define IDB_TASTER_DEFAULT_DOWN         141
#define IDB_TASTER_DEFAULT_UP           142
#define IDB_TOOLBAR_DISABLE             143
#define IDB_TOOLBAR_ENABLE              144
#define IDB_TOOLBAR_HOVER               145
#define IDB_VOTING                      146
#define IDI_ICON1                       200
#define IDI_SEARCH01                    201
#define IDI_SEARCH02                    202
#define IDI_SEARCH03                    203
#define IDI_SEARCH04                    204
#define IDI_SEARCH05                    205
#define IDI_SEARCH06                    206
#define IDI_SEARCH07                    207
#define IDI_SEARCH08                    208
#define IDI_SEARCH09                    209
#define IDI_SEARCH10                    210
#define IDI_SEARCH11                    211
#define IDI_TABCTRLBAR                  212
#define IDR_POPUP_VIEW_RUNNING          278
#define IDC_ADDRESS_COUNT_EDIT          1000
#define IDC_ADDRESS_COUNT_SPIN          1001
#define IDC_ADDRESS_STATIC              1002
#define IDC_AKTOREN_RADIO               1003
#define IDC_ANI                         1004
#define IDC_BACK                        1005
#define IDC_BG_COLOR                    1006
#define IDC_BG_COLOR_STATIC             1007
#define IDC_BG_STATIC                   1008
#define IDC_BITMAP_BUTTON               1009
#define IDC_BITMAP_EDIT                 1010
#define IDC_BITMAP_FRAME                1011
#define IDC_BITMAP_STATIC               1012
#define IDC_BUILD_STATIC                1013
#define IDC_BUTTON1                     1014
#define IDC_CARD_COMBO                  1015
#define IDC_CARD_IDENTIFIER             1016
#define IDC_COLUMN_EDIT                 1017
#define IDC_COLUMN_SPIN                 1018
#define IDC_COLUMN_STATIC               1019
#define IDC_COMPILE_DATE_STATIC         1020
#define IDC_CONNECTION_TABLE_RADIO      1021
#define IDC_COSIVIS_RADIO               1022
#define IDC_CROSS_RADIO                 1023
#define IDC_CROSS_STATIC                1024
#define IDC_DESCRIPTION_EDIT            1025
#define IDC_DEVELOPER                   1026
#define IDC_DEVELOPER_STATIC            1027
#define IDC_DEVICE_COMBO                1028
#define IDC_DEVICEID_STATIC             1029
#define IDC_DEVICENAME                  1030
#define IDC_DEVICENAME_STATIC           1031
#define IDC_DIRECTION_CHECK             1032
#define IDC_DISK                        1033
#define IDC_DOT_RADIO                   1034
#define IDC_DOT_STATIC                  1035
#define IDC_DOWN_RADIO                  1036
#define IDC_EASYPORT_RADIO              1037
#define IDC_EDIT_BLUE                   1038
#define IDC_EDIT_GREEN                  1039
#define IDC_EDIT_HUE                    1040
#define IDC_EDIT_RED                    1041
#define IDC_EDIT_SAT                    1042
#define IDC_EDIT_VAL                    1043
#define IDC_EDITABLE                    1044
#define IDC_EIGENER_DDE_SERVER_EDIT     1045
#define IDC_EMAIL                       1046
#define IDC_EMAIL_STATIC                1047
#define IDC_ERROR_EDIT                  1048
#define IDC_EXCEL_RADIO                 1049
#define IDC_EZDDE_RADIO                 1050
#define IDC_FAKTOR_EDIT                 1051
#define IDC_FG_COLOR                    1052
#define IDC_FG_COLOR_STATIC             1053
#define IDC_FG_STATIC                   1054
#define IDC_FILE_HEX_ADDR               1055
#define IDC_FILE_NAME_EDIT              1056
#define IDC_FILE_SELECT_BUTTON          1057
#define IDC_FILE_STATIC                 1058
#define IDC_FILE_TYPE                   1059
#define IDC_FILENAME                    1060
#define IDC_FILENAME_EDIT               1061
#define IDC_FILENAME_STATIC             1062
#define IDC_FLAG_ANIMATION              1063
#define IDC_FOLDER_PAGE_EDIT            1064
#define IDC_FORMEL_STATIC               1065
#define IDC_FRAME_STATIC                1066
#define IDC_FREE_MEMORY                 1067
#define IDC_FREE_STORAGE                1068
#define IDC_FUNCTION_COMBO              1069
#define IDC_FUTURE                      1070
#define IDC_GITTERRASTER_STATIC         1071
#define IDC_GRID_CHECK                  1072
#define IDC_GRID_HEIGHT                 1073
#define IDC_GRID_HEIGHT_SPIN            1074
#define IDC_GRID_WIDHT                  1075
#define IDC_GRID_WIDTH_SPIN             1076
#define IDC_GRID_X_EDIT                 1077
#define IDC_GRID_X_STATIC               1078
#define IDC_GRID_Y_EDIT                 1079
#define IDC_GRID_Y_STATIC               1080
#define IDC_HEADER                      1081
#define IDC_HIGH_EDIT                   1082
#define IDC_HIGH_SPIN                   1083
#define IDC_HIGHTIME_STATIC             1084
#define IDC_IMAGE_STATIC                1085
#define IDC_IMAGE1_STATIC               1086
#define IDC_IMAGE2_STATIC               1087
#define IDC_INPORT1_RADIO               1088
#define IDC_INPORT2_RADIO               1089
#define IDC_INPUT_COUNT_EDIT            1090
#define IDC_INPUT_COUNT_SPIN            1091
#define IDC_INPUT_STATIC                1092
#define IDC_ITEM_EDIT                   1093
#define IDC_ITEM_STATIC                 1094
#define IDC_ITEMHEADER_STATIC           1095
#define IDC_JVM_LIST                    1096
#define IDC_JVM_SELECTION_TITLE         1097
#define IDC_KANAL_EDIT                  1098
#define IDC_LANGUAGE_COMBO              1099
#define IDC_LANGUAGE_STATIC             1100
#define IDC_LINE_RADIO                  1101
#define IDC_LINE_STATIC                 1102
#define IDC_LOW_EDIT                    1103
#define IDC_LOW_SPIN                    1104
#define IDC_LOWTIME_STATIC              1105
#define IDC_MAIL_STATIC                 1106
#define IDC_MEMORY                      1107
#define IDC_METANAME_COMBO              1108
#define IDC_MODEL_RADIO                 1109
#define IDC_NUM_DEVICES                 1110
#define IDC_NUM_SUBDEVICES              1111
#define IDC_OBJECT_TREE                 1112
#define IDC_OBJEKTID_STATIC             1113
#define IDC_OPERATION                   1114
#define IDC_OUPUT_STATIC                1115
#define IDC_OUTPORT1_RADIO              1116
#define IDC_OUTPORT2_RADIO              1117
#define IDC_OUTPUT_COUNT_EDIT           1118
#define IDC_OUTPUT_COUNT_SPIN           1119
#define IDC_OUTPUT_STATIC               1120
#define IDC_PANEL_RADIO                 1121
#define IDC_PARAMFRAME_STATIC           1122
#define IDC_PASSWD_EDIT                 1123
#define IDC_PASSWD_STATIC               1124
#define IDC_PASSWD1_EDIT                1125
#define IDC_PASSWD1_STATIC              1126
#define IDC_PASSWD2_EDIT                1127
#define IDC_PASSWD2_STATIC              1128
#define IDC_PIN_CASCADE_IN              1129
#define IDC_PIN_CASCADE_OUT             1130
#define IDC_PIN_DIRECTION               1131
#define IDC_PLUGINVERSION               1132
#define IDC_PORT_EDIT                   1133
#define IDC_PREVIEV_EDIT                1134
#define IDC_PREVIEW_STATIC              1135
#define IDC_PROCESS_STATIC              1136
#define IDC_PRODUCER                    1137
#define IDC_PRODUCER_URL                1138
#define IDC_PRODUCER_URL_STATIC         1139
#define IDC_PRODUCERNAME_STATIC         1140
#define IDC_PROGRAMM_BUILD              1141
#define IDC_PROGRAMM_BUILD_LABEL        1142
#define IDC_PROGRAMM_VERSION            1143
#define IDC_PROGRAMMER                  1144
#define IDC_PROGRAMMER_URL              1145
#define IDC_PROGRAMMER_URL_STATIC       1146
#define IDC_PROGRAMMER2                 1147
#define IDC_PROGRAMMERNAME_STATIC       1148
#define IDC_PRS_HIGH_ASYNC              1149
#define IDC_PRS_HIGH_SYNC               1150
#define IDC_PRS_LOW_ASYNC               1151
#define IDC_PRS_LOW_SYNC                1152
#define IDC_PRS_NONE                    1153
#define IDC_RADIO2                      1154
#define IDC_RES_HIGH_ASYNC              1155
#define IDC_RES_HIGH_SYNC               1156
#define IDC_RES_LOW_ASYNC               1157
#define IDC_RES_LOW_SYNC                1158
#define IDC_RES_NONE                    1159
#define IDC_ROW_EDIT                    1160
#define IDC_ROW_SPIN                    1161
#define IDC_ROW_STATIC                  1162
#define IDC_SELECT_FILE                 1163
#define IDC_SERVER_EDIT                 1164
#define IDC_SERVER_STATIC               1165
#define IDC_SERVERHEADER_STATIC         1166
#define IDC_SPIN_BLUE                   1167
#define IDC_SPIN_GREEN                  1168
#define IDC_SPIN_HUE                    1169
#define IDC_SPIN_RED                    1170
#define IDC_SPIN_SAT                    1171
#define IDC_SPIN_VAL                    1172
#define IDC_STATIC_FRAME                1173
#define IDC_STATIC_HSB_RECT             1174
#define IDC_STATIC_NEW                  1175
#define IDC_STATIC_OLD                  1176
#define IDC_STATIC_PALETTE              1177
#define IDC_STATIC_RGB_RECT             1178
#define IDC_TABLE_STATIC                1179
#define IDC_TAKT_STATIC                 1180
#define IDC_TASTER_RADIO                1181
#define IDC_TOPIC_EDIT                  1182
#define IDC_TOPIC_STATIC                1183
#define IDC_TOPICHEADER_STATIC          1184
#define IDC_UNKNOWN_RADIO               1185
#define IDC_UP_RADIO                    1186
#define IDC_URL                         1187
#define IDC_URL_STATIC                  1188
#define IDC_USE_IT                      1189
#define IDC_VERSION                     1190
#define IDC_VERSION_STATIC              1191
#define IDC_VORSCHAU_STATIC             1192
#define IDC_VOTE_1                      1193
#define IDC_VOTE_2                      1194
#define IDC_VOTE_3                      1195
#define IDC_VOTE_4                      1196
#define IDC_VOTE_5                      1197
#define IDC_VOTE_6                      1198
#define IDC_VOTE_7                      1199
#define IDC_VOTE_STATIC                 1200
#define IDC_WARNING_STATIC              1201
#define IDC_WIZARD_BITMAP               1202
#define IDC_X_SPIN                      1203
#define IDC_Y_SPIN                      1204
#define IDC_ZOOM_EDIT                   1205
#define IDC_ZOOM_SPIN                   1206
#define IDC_ZOOM_STATIC                 1207
#define IDD_ABOUTBOX                    2000
#define IDD_COMMON_OPTIONS              2001
#define IDD_DDE_COSIVIS_PROPERTIES      2002
#define IDD_DDE_EXCEL_PROPERTIES        2003
#define IDD_DDE_PARAM                   2004
#define IDD_DDE_PARAM_WIZARD            2005
#define IDD_DDE_SELECT_APPLICATION_PAGE 2006
#define IDD_DDE_UNKNOWN_PROPERTIES      2007
#define IDD_DDEIN_COSIVIS_PROPERTIES    2008
#define IDD_DDEIN_EASYPORT_PROPERTIES   2009
#define IDD_DDEIN_END_PAGE              2010
#define IDD_DDEIN_START_PAGE            2011
#define IDD_DDEOUT_COSIVIS_PROPERTIES   2012
#define IDD_DDEOUT_EASYPORT_PROPERTIES  2013
#define IDD_DDEOUT_END_PAGE             2014
#define IDD_DDEOUT_START_PAGE           2015
#define IDD_DEMULTIPLEXER_PARAM         2016
#define IDD_DEVCONFIG                   2017
#define IDD_DIALOG_COLORS               2018
#define IDD_DIVIDER_PARAM               2019
#define IDD_EXPORT_DIALOG               2020
#define IDD_EZDDE_PROPERTIES            2021
#define IDD_FIND_FILE                   2022
#define IDD_GUI_PAGE                    2023
#define IDD_LOCK_DOCUMENT               2024
#define IDD_MULTIPLEXER_PARAM           2025
#define IDD_OBJECT_BAR                  2026
#define IDD_OBJECT_PROPERTY             2027
#define IDD_OBJECT_TAB_CONTROL          2028
#define IDD_OSZI_BAR                    2029
#define IDD_OSZI_OPTIONS                2030
#define IDD_OSZI_PAGE                   2031
#define IDD_PLUGIN_OBJECT_OPTIONS       2032
#define IDD_POWERTASTER_PARAM           2033
#define IDD_PRIMARY_OBJECT_PROPERTY     2034
#define IDD_SCRIPT_ERROR_DIALOG         2035
#define IDD_SCRIPT_OBJECT               2036
#define IDD_SCRIPT_OBJECTS              2037
#define IDD_SECONDARY_OBJECT_PROPERTY   2038
#define IDD_SELECT_JVM                  2039
#define IDD_SERIEL_IN_OPTION            2040
#define IDD_SERIEL_OUT_OPTION           2041
#define IDD_TAKT_PARAM                  2042
#define IDD_TASTER_PARAM                2043
#define IDD_UNLOCK_DOCUMENT             2044
#define IDD_VOTE_FOR_THE_FUTURE         2045
#define IDR_COLORSTYPE                  3000
#define IDR_DIGITATYPE                  3001
#define IDR_MAINFRAME_FREE              3002
#define IDR_OSZI_TOOLBAR                3003
#define IDR_PAL_TYPE                    3004
#define IDR_POPUP_BITMAP_OBJECT         3005
#define IDR_POPUP_DDE_OBJECT            3006
#define IDR_POPUP_DDEIN_ERROR_OBJECT    3007
#define IDR_POPUP_DDEIN_OBJECT          3008
#define IDR_POPUP_DDEOUT_ERROR_OBJECT   3009
#define IDR_POPUP_DDEOUT_OBJECT         3010
#define IDR_POPUP_ELECTRIC_OBJECT       3011
#define IDR_POPUP_LINK_OBJECT           3012
#define IDR_POPUP_OBJECT                3013
#define IDR_POPUP_OSZI                  3014
#define IDR_POPUP_PALETTE               3015
#define IDR_POPUP_SCRIPT_OBJECT         3016
#define IDR_POPUP_SERIELIN_OBJECT       3017
#define IDR_POPUP_SERIELOUT_OBJECT      3018
#define IDR_POPUP_TEXT_OBJECT           3019
#define IDR_POPUP_VIEW                  3020
#define IDR_POPUP_VIEWPOINT_OBJECT      3021
#define IDR_SCRIPTTYPE                  3022
#define ID_ALIGN_DOWN                   22000
#define ID_ALIGN_LEFT                   22001
#define ID_ALIGN_RIGHT                  22002
#define ID_ALIGN_UP                     22003
#define ID_CONNECTOR_FLYOVER            22004
#define ID_DATEI_EXPORT                 22005
#define ID_DATEI_EXPORT_JNI             22006
#define ID_DATEI_EXPORT_PNG             22007
#define ID_DATEI_EXPORT_WEBSHARE        22008
#define ID_EDIT_PALETTE                 22009
#define ID_EIGENSCHAFTEN_OSZILOSKOPE    22010
#define ID_EXPORT_WEBSHARE              22011
#define ID_EXTENDED_OPTION              22012
#define ID_FULLSCREEN                   22013
#define ID_GRID                         22014
#define ID_INSERT_OBJECT                22015
#define ID_INSERT_REMOVE_VIEWPOINT      22016
#define ID_INSERT_STROKE_SEGMENT        22017
#define ID_OBJECT_BASICS                22018
#define ID_OBJECT_CUT                   22019
#define ID_OBJECT_EXTENDED_OPTION       22020
#define ID_OBJECT_HELP                  22021
#define ID_OBJECT_OPTION                22022
#define ID_OBJECT_TAB_CTRL              22023
#define ID_OBJECT_TO_BACK               22024
#define ID_OBJECT_TO_FRONT              22025
#define ID_OPTIONS                      22026
#define ID_OPTIONS_TOOLBAR              22029
#define ID_OSZI_PRINT                   22030
#define ID_OSZI_ZOOM_DECREASE           22031
#define ID_OSZI_ZOOM_INCREASE           22032
#define ID_OSZIGRID                     22033
#define ID_PALETTE_AUTOLAYOUT           22034
#define ID_PROTECT_DOCUMENT             22035
#define ID_REMOVE_STROKE_SEGMENT        22036
#define ID_SET_GRID                     22037
#define ID_START_SIMULATION             22038
#define ID_START_SIMULATION_RECORD      22039
#define ID_STOP                         22040
#define ID_UPDATE_DDE_OBJECT            22041
#define ID_VIEW_OBJECT_BAR              22042
#define ID_VIEW_OSZI_BAR                22043
#define ID_ZOOM_DECREASE                22044
#define ID_ZOOM_FIT                     22045
#define ID_ZOOM_INCREASE                22046
#define ID_ZOOM_STANDARD                22047
#define ID_TOOLS_START                  22100
#define ID_TOOLS_END                    22200
#define ID_POPUP_toolStart              48000
#define ID_POPUP_toolEnd                48099
#define ID_POPUP_dialogStart            48100
#define ID_POPUP_dialogEnd              48199
#define OBJEKTE                         61500

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        279
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1223
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
