package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 17:58:17 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.Trace;
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;

public class CaseLayout extends _dbCaseLayout
{
   ElectricCase currentElectricCase = null;
   ArrayList    casePins            = null;

   protected void reserveResources(ElectricCase _currentElectricCase)
   {
//        System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
      currentElectricCase = _currentElectricCase;

      casePins = super.getCasePins();
      Iterator iter = casePins.iterator();
      while(iter.hasNext())
      {
         CasePin casePin= (CasePin)iter.next();
         casePin.reserveResources(this);
      }
   }

   public ElectricCase getCurrentElectricCase()
   {
    return currentElectricCase;
   }

   /**
    *
    */
   public ArrayList getCasePins()
   {
      if(casePins!=null)
         return casePins;

      return super.getCasePins();
   }


    public String toString()
    {
        return "["+super.toString()+"]@"+ this.hashCode();
    }
}
