package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 17:58:17 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.Trace;
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.*;

public class CasePin extends _dbCasePin
{
   private CaseLayout currentCaseLayout = null;

   public static CasePin createInstance(String description, int number, CaseLayout cl, long x, long y)
   {
   	  return _dbCasePin.createInstance(description, y,cl,x,number);
   }
   
   
   public Point getPosition()
   {
    return new Point((int)x,(int)y);
   }
   
   public void setBounds(Rectangle rect, boolean commit)
   {
   	  x = rect.x;
      y = rect.y;
      if(commit)
        commit();
   }
   
   public Rectangle getBounds()
   {
   	  return new Rectangle((int)x,(int)y,20,20);
   }
   
   public CaseLayout getCaseLayout()
   {
        if(currentCaseLayout!=null)
            return currentCaseLayout;
        return super.getCaseLayout();
   }

   public ElectricCase getCurrentElectricCase()
   {
       return getCaseLayout().getCurrentElectricCase();
   }

   protected void reserveResources(CaseLayout _currentCaseLayout)
   {
//      System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
      currentCaseLayout = _currentCaseLayout;
   }

    public String toString()
    {
        return "["+super.toString()+"]@"+ this.hashCode();
    }
}
