package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 17:58:17 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.Trace;
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;

public class DependencyPin extends _dbDependencyPin
{
  static public DependencyPin createInstance( _dbObjectPin2CasePin _objectPin2CasePin,_dbCasePin _casePin, _dbCaseDependency _caseDependency )
  {
    return _dbDependencyPin.createInstance( _casePin, _caseDependency, _objectPin2CasePin );
  }
    public String toString()
    {
        return "["+super.toString()+"]@"+ this.hashCode();
    }
}
