package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 18:01:51 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.Trace;
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.awt.Rectangle;
import java.sql.*;
import java.util.ArrayList;


public class ElectricCase extends _dbElectricCase
{
    ArrayList  object2CaseList  = null;
    CaseLayout caseLayout  = null;

    int partNum;

    public void setBounds(Rectangle rect, boolean commit)
    {
      x = rect.x;
      y = rect.y;
      width = rect.width;
      height = rect.height;
      if(commit)
        commit();
    }
    
    public Rectangle getBounds()
    {
      return new Rectangle((int)x,(int)y,width,height);
    }
    
    public static ElectricCase createInstance(String name,String docUrl, CaseLayout cl)
    {
     return _dbElectricCase.createInstance(50,50,10,cl,name,10,docUrl,null/*iconName*/); 
    }

    public void setPartNum(int num)
    {
      partNum = num;
    }

    public int getPartNum()
    {
      return partNum;
    }

    /**
     * cache the stuff
     */
    public ArrayList getObject2Cases()
    {
        if(object2CaseList!=null)
           return object2CaseList;

//        ArrayList result = new ArrayList();
//        ArrayList c2o = getObject2Cases();
//        Iterator iter = c2o.iterator();
//        while(iter.hasNext())
//        {
//            Object2Case eobj = (Object2Case)iter.next();
//            result.add(eobj.getObject());
//        }
//
        return super.getObject2Cases();
    }

    public ArrayList getElectricObjects()
    {
      ArrayList result = new ArrayList();
    	Iterator iter = getObject2Cases().iterator();
      while (iter.hasNext())
			{
				Object2Case element = (Object2Case) iter.next();
				result.add(element.getObject());
			}
    	return result;
    }
    
    /**
     *
     */
    public CasePin getPin(long number)
    {
        Iterator iter = getCaseLayout().getCasePins().iterator();
        while(iter.hasNext())
        {
            CasePin opin= (CasePin)iter.next();
            if(opin.getNumber()==number)
                return opin;
        }
        return null;
    }

    /**
     *
     */
    public void reserveResources()
    {
        System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
        caseLayout = super.getCaseLayout();
        caseLayout.reserveResources(this);

        object2CaseList = getObject2Cases();
        Iterator iter  = object2CaseList.iterator();
        while(iter.hasNext())
        {
          Object2Case    o2c  = (Object2Case)iter.next();
          //ElectricObject eobj = o2c.getObject();
          o2c.reserveResources(this);
        }
    }

    public CaseLayout getCaseLayout()
    {
      if(caseLayout!=null)
         return caseLayout;

      return super.getCaseLayout();
    }


    public String toString()
    {
        return getName();
    }
}
