package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Fri Sep 20 10:33:24 GMT+02:00 2002
 */
import de.freegroup.digitalsimulator.Trace;
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;
//import de.freegroup.digitalsimulator.plugin.export.wired.ObjectFactory;

public class MacroPinMapping extends _dbMacroPinMapping
{
   ElectricObject from;
   ElectricObject to;

   public static MacroPinMapping createInstance( int roPinNum, RelatedObject rObj, int eoPinNum,ElectricObject eObj)
   {
    return _dbMacroPinMapping.createInstance(eoPinNum, roPinNum, eObj,rObj);
   }
   
   protected void reserveResources(ElectricObject _from, ElectricObject _to)
   {
      from = _from;
      to   = _to;
   }

   protected CasePin getMappedCasePin()
   {
      return to.getCasePin(relatedObjectPinNum);
   }
}
