package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Mon Jan 26 22:21:06 CET 2004
 */
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.*;
import de.freegroup.digitalsimulator.Trace;

public class ObjectPin extends _dbObjectPin
{
  static public ObjectPin createInstance( String  _description, int  _number, _dbObjectLayout _objectLayout )
  {
   return _dbObjectPin.createInstance(_description, 10,10,_objectLayout,_number ); 
  }


  public Point getPosition()
  {
    return new Point((int)x,(int)y);
  }
  
  public void setAbsoluteBounds(Rectangle rect, boolean commit)
  {
    // the position will bee stored ralative to its parent
    //
    Point parentPos = getObjectLayout().getElectricObject().getPosition();
    x = rect.x-parentPos.x;
    y = rect.y-parentPos.y;
    if(commit)
      commit();
  }
  
  public Rectangle getAbsoluteBounds()
  {
    Point parentPos = getObjectLayout().getElectricObject().getPosition();
    return new Rectangle((int)x+parentPos.x,(int)y+parentPos.y,20,20);
//    Rectangle rect= new Rectangle((int)x+parentPos.x,(int)y+parentPos.y,20,20);
//    System.out.println(rect);
//    return rect;
  }
}
