package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Mon Jan 26 21:57:49 CET 2004
 */
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;
import de.freegroup.digitalsimulator.Trace;

public class ObjectPin2CasePin extends _dbObjectPin2CasePin
{
  Object2Case currentObject2Case = null;
  CasePin      currentCasePin    = null;

  static public ObjectPin2CasePin createInstance( _dbCasePin _casePin, _dbObject2Case _object2Case, _dbObjectPin _objectPin )
  {
    return createInstance(_objectPin, _casePin, _object2Case);
  }
  
  protected void reserveResources(Object2Case _object2Case)
  {
//        System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
    currentObject2Case = _object2Case;
    long number = super.getCasePin().getNumber();

    // get the reserved(!!) casePin from the reserved(!!) case.
    currentCasePin = currentObject2Case.getCurrentElectricCase().getPin(number);
  }

  public CasePin getCasePin()
  {
    if(currentCasePin!=null)
      return currentCasePin;

    return super.getCasePin();
  }

  public String toString()
  {
    return "["+super.toString()+"]@"+ this.hashCode();
  }
}
