package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 17:58:17 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;
import Trace;

public class CasePin extends _dbCasePin
{
   private CaseLayout currentCaseLayout = null;

   public CaseLayout getCaseLayout()
   {
        if(currentCaseLayout!=null)
            return currentCaseLayout;
        return super.getCaseLayout();
   }

   public ElectricCase getCurrentElectricCase()
   {
       return getCaseLayout().getCurrentElectricCase();
   }

   protected void reserveResources(CaseLayout _currentCaseLayout)
   {
//      System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
      currentCaseLayout = _currentCaseLayout;
   }

    public String toString()
    {
        return "["+super.toString()+"]@"+ this.hashCode();
    }
}
