package de.freegroup.digitalsimulator.export.wired.db;

/**
 * Class generated by automatic ClassGenerator
 * Date: Wed Feb 27 17:58:16 GMT+01:00 2002
 */
import de.freegroup.digitalsimulator.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;
import Trace;

public class ObjectPin extends _dbObjectPin
{
   Object2Case currentObject2Case = null;
   CasePin      currentCasePin    = null;

   protected void reserveResources(Object2Case _object2Case)
   {
//        System.out.println("reserve "+getClass().getName()+"@"+this.hashCode());
      currentObject2Case = _object2Case;
      long number = super.getCasePin().getNumber();

      // get the reserved(!!) casePin from the reserved(!!) case.
      currentCasePin = currentObject2Case.getCurrentElectricCase().getPin(number);
   }

   public CasePin getCasePin()
   {
      if(currentCasePin!=null)
        return currentCasePin;

      return super.getCasePin();
   }

    public String toString()
    {
        return "["+super.toString()+"]@"+ this.hashCode();
    }
}
