/*
 * Created on Jan 15, 2004
 *
 * To change the template for this generated file go to
 * Window>Preferences>Java>Code Generation>Code and Comments
 */
package de.freegroup.digitalsimulator;

/**
 * @author Administrator
 *
 * To change the template for this generated type comment go to
 * Window>Preferences>Java>Code Generation>Code and Comments
 */
public class Document
{
  public static String getCurrentAsXML()
  {
    if (Application.isRunningInDigiSim())
    {
      return n_getCurrentAsXML();
    }
    return "";
  }
  
  public static void setCurrentDocumentation(String docAsXml)
  {
    if (Application.isRunningInDigiSim())
    {
      n_setCurrentDocumentation(docAsXml);
    }
    else
    {
      testDoku = docAsXml; 
    }
   }
  
  public static String getCurrentDocumentation()
  {
    if (Application.isRunningInDigiSim())
    {
      return n_getCurrentDocumentation();
    }
    return "";
  }
  
  
  native public static String n_getCurrentAsXML();
  native public static void   n_setCurrentDocumentation(String docAsXml);
  native public static String n_getCurrentDocumentation();
  
  
  private static String testDoku=
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"+
"<!--Sample XML file generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->"+
"<DocumentDocumentation>"+
"  <version>"+
"    <v_01x00>"+
"      <author>"+
"        <firstName>firstName</firstName>"+
"        <lastName>lastName</lastName>"+
"        <street>street</street>"+
"        <number>number</number>"+
"        <city>city</city>"+
"        <zipCode>zipCode</zipCode>"+
"      </author>"+
"      <circuit>"+
"        <name>name</name>"+
"        <shortDescription>shortDescription</shortDescription>"+
"        <longDescription>longDescription</longDescription>"+
"      </circuit>"+
"    </v_01x00>"+
"  </version>"+
"</DocumentDocumentation>";

}
